
FROM openjdk:11-jre-slim-buster
ENV JAR_NAME prime-number-service-1.0.0.jar
COPY prime-number-service-1.0.0.jar /home/appuser/prime-number-service-1.0.0.jar
ENTRYPOINT ["java","-jar","/home/appuser/prime-number-service-1.0.0.jar"]

